### ISSUE TITLE
still working? login failed

### ISSUE THREAD

**Issue by TomTomNavigator** [nicksinger/adp_downloader#4]
Hey, is this still working? afaik adpworld changed their login that username and company is now combined in one value (username) - maybe that's the issue?

```
Welcome! Starting up the adpworld.de scraper.
Trying to log in… Failed…
Please check your credentials!
```

**Comment by nicksinger** [comment]
Hey! I haven't run it for some time and apparently you're right and the new login flow breaks it. I will look into it and let you know once it is working again - thanks for your report :)
